project_id = "jmzmwkfctefzokhesxjf"

[functions.transcribe-audio-live]
verify_jwt = false

[functions.transcribe-audio-batch]
verify_jwt = false

[functions.transcribe-audio-batch-status]
verify_jwt = false

[functions.generate-note]
verify_jwt = false

[functions.search-patient-context]
verify_jwt = false

[functions.edit-note-voice]
verify_jwt = false

[functions.auth-check]
verify_jwt = false

[functions.start-batch-latest]
verify_jwt = false

[functions.update-visit-summary]
verify_jwt = false

[functions.transcribe-stream-start]
verify_jwt = false
